// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace Aryan_Patel_COMP212_Sec003_Lab05ML.Model
{
    public class ModelInput
    {
        [ColumnName("STG"), LoadColumn(0)]
        public float STG { get; set; }


        [ColumnName("SCG"), LoadColumn(1)]
        public float SCG { get; set; }


        [ColumnName("STR"), LoadColumn(2)]
        public float STR { get; set; }


        [ColumnName("LPR"), LoadColumn(3)]
        public float LPR { get; set; }


        [ColumnName("PEG"), LoadColumn(4)]
        public float PEG { get; set; }


        [ColumnName("UNS"), LoadColumn(5)]
        public string UNS { get; set; }


    }
}
